### ISSUE TITLE
net-proxy/clash: insufficient privileges for clash to write files in /etc/clash directory

### ISSUE THREAD

**Issue by ghost** [Gentoo-zh/gentoo-zh#2322]
When Starting clash.service with `/etc/clash/config.yaml` like below, 
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 1.1.1.1
  fallback:
    - 1.0.0.1
    - 8.8.8.8
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

proxy-providers:
  cordcloud:
    type: http
    url: "https://xxx"
    interval: 3600
    path: ./xxx.yaml
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://xxxx

rules:
   ...
```

clash.service will be failed to start due to insufficient privileges for clash to write files in `/etc/clash` directory.

The main cause is that the `DynamiUser=` in the `clash.service file` implies `ProtectSystem=strict`, which will make systemd mount `/etc/` read-only for clash.

Maybe we need to add `ReadWritePath=/etc/clash` in `clash.service` file to make `clash` free to write configuration files and `cache.db` file in `/etc/clash`.
